packages:
  - .
autoInstallPeers: false
minimumReleaseAge: 0

patchedDependencies:
  next@16.3.5: patches/next@16.3.5.patch
allowBuilds:
  '@sentry/cli': true
  core-js: true
  sharp: true
publicHoistPattern:
  - '*import-in-the-middle*'
  - '*require-in-the-middle*'
