name: ✨ Feature/Enhancement
description: Request a new feature or enhancement
title: <title>
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for the enhancement you are proposing.
      options:
        - label: I have searched the existing feature requests
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the new feature or enhancement you are proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Provide a use case or scenario where this feature or enhancement would be beneficial.

  - type: textarea
    attributes:
      label: Proposed Solution
      description: If you have a specific solution in mind, please describe it here.

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information or context that might be relevant to the feature/enhancement request.

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature or enhancement you are proposing!

        Tip: You can attach images or other files by clicking this area to highlight it and then dragging files in.
